apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse_proxy
  labels:
    service: reverse_proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverse_proxy
  template:
    metadata:
      labels:
        service: reverse_proxy
    spec:
      containers:
      - name: reverse_proxy
        image: kelue/reverse-proxy
        ports:
        - containerPort: 8080
      restartPolicy: Always