apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverse_proxy
  name: reverse_proxy-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverse_proxy
